{"metadata":{"modules":[{"name":"MessagingSDK"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildUI"},{"kind":"text","text":"("},{"kind":"externalParam","text":"engines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Engine","preciseIdentifier":"s:12MessagingAPI6EngineP"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"configs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"title":"buildUI(engines:configs:)","role":"symbol","externalID":"s:12MessagingSDK0A0C7buildUI7engines7configsSo16UIViewControllerCSay0A3API6Engine_pG_Say17SDKConfigurations13Configuration_pGtKF","roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/buildUI(engines:configs:)-8o1v"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging"]]},"abstract":[{"text":"Builds the Messaging UI ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/messagingsdk\/messaging\/buildui(engines:configs:)-8o1v"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buildUI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"engines","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Engine","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI6EngineP"},{"text":"], ","kind":"text"},{"text":"configs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"text":"] = []) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}]}]},{"kind":"parameters","parameters":[{"name":"engines","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ordered list of engines that will be part of the conversation"}]}]},{"name":"configs","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Configurations for each of your engines"}]}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"An instance of ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":" which starts with the first engine in ","type":"text"},{"type":"codeVoice","code":"engines"}]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"name":"Throws","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If no engines were passed"}]}],"type":"aside"}]}],"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging/buildUI(engines:configs:)-8o1v":{"type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/buildUI(engines:configs:)-8o1v","role":"symbol","abstract":[{"text":"Builds the Messaging UI ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/messagingsdk\/messaging\/buildui(engines:configs:)-8o1v","kind":"symbol","title":"buildUI(engines:configs:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buildUI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"engines","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:12MessagingAPI6EngineP","text":"Engine","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"configs","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","text":"Configuration","kind":"typeIdentifier"},{"text":"]) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"title":"MessagingSDK","type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","abstract":[],"url":"\/documentation\/messagingsdk","kind":"symbol","role":"collection"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Messaging"}],"navigatorTitle":[{"kind":"identifier","text":"Messaging"}],"url":"\/documentation\/messagingsdk\/messaging","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The Messaging class coordinates Zendesk’s product UI engines,"},{"type":"text","text":" "},{"type":"text","text":"to allow them to work seamlessly in a single unified messaging interface."}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","title":"Messaging"}},"variantOverrides":[{"patch":[{"value":"ZDKClassicMessaging","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/title","op":"replace"},{"value":[{"text":"ZDKClassicMessaging","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/fragments","op":"replace"},{"value":[{"text":"ZDKClassicMessaging","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}