{"variants":[{"paths":["\/documentation\/messagingsdk\/messaging\/getconfigurations()"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getConfigurations","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(cs)ZDKConfigurations","text":"Configurations","kind":"typeIdentifier"}]}]}],"identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/getConfigurations()","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getConfigurations","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(cs)ZDKConfigurations","text":"Configurations","kind":"typeIdentifier"}],"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"MessagingSDK"}],"extendedModule":"MessagingSDK","symbolKind":"method","externalID":"s:12MessagingSDK0A0C17getConfigurations17SDKConfigurations0D0CyF","title":"getConfigurations()"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging"]]},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MessagingAPIProtocol.getConfigurations()"},{"type":"text","text":"."}],"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging/getConfigurations()":{"title":"getConfigurations()","url":"\/documentation\/messagingsdk\/messaging\/getconfigurations()","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/getConfigurations()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getConfigurations","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(cs)ZDKConfigurations","text":"Configurations","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"kind":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"title":"MessagingSDK","type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","abstract":[],"url":"\/documentation\/messagingsdk","kind":"symbol","role":"collection"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Messaging"}],"navigatorTitle":[{"kind":"identifier","text":"Messaging"}],"url":"\/documentation\/messagingsdk\/messaging","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The Messaging class coordinates Zendesk’s product UI engines,"},{"type":"text","text":" "},{"type":"text","text":"to allow them to work seamlessly in a single unified messaging interface."}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","title":"Messaging"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"ZDKClassicMessaging","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/title"},{"op":"replace","value":[{"text":"ZDKClassicMessaging","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKClassicMessaging"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/navigatorTitle"}]}]}