{"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/messagingsdk\/messaging\/messagingapiprotocol-implementations"]}],"kind":"article","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"MessagingSDK"}],"role":"collectionGroup","title":"MessagingAPIProtocol Implementations","roleHeading":"API Collection"},"identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/MessagingAPIProtocol-Implementations","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/getBotAgentDetails()","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/getConfigurations()","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/getConversationLog()","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/getTransferOptions()"],"title":"Instance Methods"}],"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"title":"MessagingSDK","type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","abstract":[],"url":"\/documentation\/messagingsdk","kind":"symbol","role":"collection"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Messaging"}],"navigatorTitle":[{"kind":"identifier","text":"Messaging"}],"url":"\/documentation\/messagingsdk\/messaging","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The Messaging class coordinates Zendesk’s product UI engines,"},{"type":"text","text":" "},{"type":"text","text":"to allow them to work seamlessly in a single unified messaging interface."}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","title":"Messaging"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging/getConfigurations()":{"title":"getConfigurations()","url":"\/documentation\/messagingsdk\/messaging\/getconfigurations()","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/getConfigurations()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getConfigurations","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(cs)ZDKConfigurations","text":"Configurations","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"kind":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging/getBotAgentDetails()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBotAgentDetails"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:12MessagingAPI12AgentDetailsV","kind":"typeIdentifier","text":"AgentDetails"}],"kind":"symbol","type":"topic","title":"getBotAgentDetails()","role":"symbol","url":"\/documentation\/messagingsdk\/messaging\/getbotagentdetails()","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/getBotAgentDetails()","abstract":[]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging/getConversationLog()":{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/getConversationLog()","role":"symbol","title":"getConversationLog()","kind":"symbol","url":"\/documentation\/messagingsdk\/messaging\/getconversationlog()","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getConversationLog","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"ConversationLogProtocol","preciseIdentifier":"s:12MessagingAPI23ConversationLogProtocolP","kind":"typeIdentifier"}]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging/getTransferOptions()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getTransferOptions","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"TransferOptionDescription","preciseIdentifier":"c:@M@MessagingAPI@objc(cs)ZDKTransferOptionDescription","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"abstract":[],"title":"getTransferOptions()","type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/getTransferOptions()","url":"\/documentation\/messagingsdk\/messaging\/gettransferoptions()","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"ZDKClassicMessaging","op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/title"},{"value":[{"kind":"identifier","text":"ZDKClassicMessaging"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/fragments"},{"value":[{"kind":"identifier","text":"ZDKClassicMessaging"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}