{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/messagingsdk\/messaginguievent\/viewwillappear"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/messagingsdk\/messaginguievent\/viewwillappear"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewWillAppear","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"}],"title":"MessagingUIEvent.viewWillAppear","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@MessagingSDK@E@ZDKClassicMessagingUIEvent@ZDKClassicMessagingUIEventViewWillAppear","modules":[{"name":"MessagingSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewWillAppear"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent"]]},"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent":{"role":"symbol","title":"MessagingUIEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingUIEvent"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagingUIEvent"}],"url":"\/documentation\/messagingsdk\/messaginguievent"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent/viewWillAppear":{"role":"symbol","title":"MessagingUIEvent.viewWillAppear","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewWillAppear","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewWillAppear"}],"url":"\/documentation\/messagingsdk\/messaginguievent\/viewwillappear"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"role":"collection","title":"MessagingSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","kind":"symbol","type":"topic","url":"\/documentation\/messagingsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKClassicMessagingUIEventViewWillAppear"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewWillAppear"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewWillAppear"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/title","value":"ZDKClassicMessagingUIEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/fragments","value":[{"kind":"identifier","text":"ZDKClassicMessagingUIEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewWillAppear\/title","value":"ZDKClassicMessagingUIEventViewWillAppear"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewWillAppear\/fragments","value":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewWillAppear"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}