{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"messaging"},{"kind":"text","text":": "},{"text":"Messaging","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","preciseIdentifier":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessaging"},{"text":", ","kind":"text"},{"text":"shouldOpenURL","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"url","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"messaging","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"Messaging"},{"text":" instance","type":"text"}],"type":"paragraph"}]},{"name":"url","content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"URL"},{"type":"text","text":" the user tapped"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"text":"Return ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":" if Messaging should handle the URL. Return "},{"type":"codeVoice","code":"false"},{"text":" if there is a specified URL flow.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"Return "},{"code":"true","type":"codeVoice"},{"text":" when there is no way to handle a specific URL and ","type":"text"},{"code":"Messaging","type":"codeVoice"},{"type":"text","text":" will handle it."}],"type":"paragraph"}],"name":"Note","style":"note"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate"]]},"variants":[{"paths":["\/documentation\/messagingsdk\/messagingdelegate\/messaging(_:shouldopenurl:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/messagingsdk\/messagingdelegate\/messaging(_:shouldopenurl:)"]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate\/messaging(_:shouldOpenURL:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","title":"messaging(_:shouldOpenURL:)","modules":[{"name":"MessagingSDK"}],"required":true,"externalID":"c:@M@MessagingSDK@objc(pl)ZDKClassicMessagingDelegate(im)messaging:shouldOpenURL:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"messaging","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessaging","text":"Messaging"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"shouldOpenURL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"messaging:shouldOpenURL:"}]},"kind":"symbol","abstract":[{"text":"Optional ","type":"text"},{"type":"codeVoice","code":"MessagingDelegate"},{"type":"text","text":" method that allows custom URL link handling."}],"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingDelegate":{"navigatorTitle":[{"text":"MessagingDelegate","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MessagingDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate","url":"\/documentation\/messagingsdk\/messagingdelegate","type":"topic","title":"MessagingDelegate","role":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging":{"navigatorTitle":[{"kind":"identifier","text":"Messaging"}],"abstract":[{"type":"text","text":"The Messaging class coordinates Zendesk’s product UI engines,"},{"type":"text","text":" "},{"type":"text","text":"to allow them to work seamlessly in a single unified messaging interface."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Messaging","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","type":"topic","url":"\/documentation\/messagingsdk\/messaging","title":"Messaging","role":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","role":"collection","url":"\/documentation\/messagingsdk","type":"topic","abstract":[],"title":"MessagingSDK","kind":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingDelegate/messaging(_:shouldOpenURL:)":{"type":"topic","kind":"symbol","required":true,"abstract":[{"text":"Optional ","type":"text"},{"type":"codeVoice","code":"MessagingDelegate"},{"type":"text","text":" method that allows custom URL link handling."}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate\/messaging(_:shouldOpenURL:)","title":"messaging(_:shouldOpenURL:)","url":"\/documentation\/messagingsdk\/messagingdelegate\/messaging(_:shouldopenurl:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"messaging","kind":"identifier"},{"kind":"text","text":"("},{"text":"Messaging","preciseIdentifier":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessaging","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"shouldOpenURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"messaging:shouldOpenURL:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"messaging:shouldOpenURL:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"messaging:shouldOpenURL:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"messaging:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","kind":"typeIdentifier","preciseIdentifier":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessaging","text":"ZDKClassicMessaging"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"messaging"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shouldOpenURL:"},{"kind":"text","text":"("},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"text":"url","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"ZDKClassicMessagingDelegate","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate\/title"},{"value":[{"kind":"identifier","text":"ZDKClassicMessagingDelegate"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/title","value":"ZDKClassicMessaging"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/fragments","value":[{"kind":"identifier","text":"ZDKClassicMessaging"}]},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate~1messaging(_:shouldOpenURL:)\/title","value":"messaging:shouldOpenURL:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"messaging:shouldOpenURL:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate~1messaging(_:shouldOpenURL:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}