{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/messagingsdk\/messaginguievent\/viewdidlayoutsubviews"]},{"paths":["\/documentation\/messagingsdk\/messaginguievent\/viewdidlayoutsubviews"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidLayoutSubviews","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewDidLayoutSubviews"}],"externalID":"c:@M@MessagingSDK@E@ZDKClassicMessagingUIEvent@ZDKClassicMessagingUIEventViewDidLayoutSubviews","roleHeading":"Case","modules":[{"name":"MessagingSDK"}],"symbolKind":"case","title":"MessagingUIEvent.viewDidLayoutSubviews","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLayoutSubviews"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent"]]},"sections":[],"kind":"symbol","references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingUIEvent"}],"type":"topic","url":"\/documentation\/messagingsdk\/messaginguievent","navigatorTitle":[{"text":"MessagingUIEvent","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent","title":"MessagingUIEvent","kind":"symbol","role":"symbol","abstract":[]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent/viewDidLayoutSubviews":{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidLayoutSubviews","navigatorTitle":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewDidLayoutSubviews"}],"title":"MessagingUIEvent.viewDidLayoutSubviews","url":"\/documentation\/messagingsdk\/messaginguievent\/viewdidlayoutsubviews","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"kind":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"abstract":[],"title":"MessagingSDK","type":"topic","url":"\/documentation\/messagingsdk","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ZDKClassicMessagingUIEventViewDidLayoutSubviews","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewDidLayoutSubviews"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewDidLayoutSubviews"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/title","value":"ZDKClassicMessagingUIEvent"},{"op":"replace","value":[{"text":"ZDKClassicMessagingUIEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/fragments"},{"value":"ZDKClassicMessagingUIEventViewDidLayoutSubviews","op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewDidLayoutSubviews\/title"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewDidLayoutSubviews\/fragments","op":"replace","value":[{"text":"ZDKClassicMessagingUIEventViewDidLayoutSubviews","kind":"identifier"}]}]}]}