{"metadata":{"modules":[{"name":"MessagingSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"viewControllerDidClose","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ZDKClassicMessagingUIEventViewControllerDidClose","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@MessagingSDK@E@ZDKClassicMessagingUIEvent@ZDKClassicMessagingUIEventViewControllerDidClose","title":"MessagingUIEvent.viewControllerDidClose","symbolKind":"case"},"identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewControllerDidClose","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/messagingsdk\/messaginguievent\/viewcontrollerdidclose"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/messagingsdk\/messaginguievent\/viewcontrollerdidclose"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewControllerDidClose","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent"]]},"abstract":[{"text":"Fired once the Messaging UI is closed and no longer visible to the user","type":"text"}],"sections":[],"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingUIEvent"}],"type":"topic","url":"\/documentation\/messagingsdk\/messaginguievent","navigatorTitle":[{"text":"MessagingUIEvent","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent","title":"MessagingUIEvent","kind":"symbol","role":"symbol","abstract":[]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent/viewControllerDidClose":{"kind":"symbol","url":"\/documentation\/messagingsdk\/messaginguievent\/viewcontrollerdidclose","role":"symbol","navigatorTitle":[{"text":"ZDKClassicMessagingUIEventViewControllerDidClose","kind":"identifier"}],"abstract":[{"text":"Fired once the Messaging UI is closed and no longer visible to the user","type":"text"}],"type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewControllerDidClose","title":"MessagingUIEvent.viewControllerDidClose","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"viewControllerDidClose","kind":"identifier"}]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"abstract":[],"title":"MessagingSDK","type":"topic","url":"\/documentation\/messagingsdk","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"ZDKClassicMessagingUIEventViewControllerDidClose","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewControllerDidClose"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"ZDKClassicMessagingUIEventViewControllerDidClose","kind":"identifier"}],"languages":["occ"]}]}},{"value":"ZDKClassicMessagingUIEvent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/fragments","value":[{"text":"ZDKClassicMessagingUIEvent","kind":"identifier"}]},{"value":"ZDKClassicMessagingUIEventViewControllerDidClose","op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewControllerDidClose\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewControllerDidClose\/fragments","value":[{"text":"ZDKClassicMessagingUIEventViewControllerDidClose","kind":"identifier"}]}]}]}