{"metadata":{"title":"MessagingUIEvent.viewDidAppear","externalID":"c:@M@MessagingSDK@E@ZDKClassicMessagingUIEvent@ZDKClassicMessagingUIEventViewDidAppear","role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"}],"roleHeading":"Case","modules":[{"name":"MessagingSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewDidAppear"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidAppear","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/messagingsdk\/messaginguievent\/viewdidappear"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/messagingsdk\/messaginguievent\/viewdidappear"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent/viewDidAppear":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewDidAppear"}],"type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidAppear","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"}],"kind":"symbol","title":"MessagingUIEvent.viewDidAppear","role":"symbol","url":"\/documentation\/messagingsdk\/messaginguievent\/viewdidappear"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"title":"MessagingSDK","type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","abstract":[],"url":"\/documentation\/messagingsdk","kind":"symbol","role":"collection"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent":{"url":"\/documentation\/messagingsdk\/messaginguievent","navigatorTitle":[{"kind":"identifier","text":"MessagingUIEvent"}],"type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingUIEvent"}],"kind":"symbol","title":"MessagingUIEvent","role":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKClassicMessagingUIEventViewDidAppear","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewDidAppear"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewDidAppear"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKClassicMessagingUIEventViewDidAppear","op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewDidAppear\/title"},{"value":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewDidAppear"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewDidAppear\/fragments"},{"value":"ZDKClassicMessagingUIEvent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/title"},{"value":[{"text":"ZDKClassicMessagingUIEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/fragments"},{"value":[{"text":"ZDKClassicMessagingUIEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/navigatorTitle"}]}]}