{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidLoad"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","metadata":{"roleHeading":"Case","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKClassicMessagingUIEventViewDidLoad","kind":"identifier"}],"modules":[{"name":"MessagingSDK"}],"externalID":"c:@M@MessagingSDK@E@ZDKClassicMessagingUIEvent@ZDKClassicMessagingUIEventViewDidLoad","title":"MessagingUIEvent.viewDidLoad"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/messagingsdk\/messaginguievent\/viewdidload"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/messagingsdk\/messaginguievent\/viewdidload"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent":{"url":"\/documentation\/messagingsdk\/messaginguievent","navigatorTitle":[{"kind":"identifier","text":"MessagingUIEvent"}],"type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingUIEvent"}],"kind":"symbol","title":"MessagingUIEvent","role":"symbol","abstract":[]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"title":"MessagingSDK","type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","abstract":[],"url":"\/documentation\/messagingsdk","kind":"symbol","role":"collection"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent/viewDidLoad":{"type":"topic","navigatorTitle":[{"text":"ZDKClassicMessagingUIEventViewDidLoad","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidLoad","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"abstract":[],"url":"\/documentation\/messagingsdk\/messaginguievent\/viewdidload","title":"MessagingUIEvent.viewDidLoad","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKClassicMessagingUIEventViewDidLoad","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKClassicMessagingUIEventViewDidLoad","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ZDKClassicMessagingUIEventViewDidLoad","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKClassicMessagingUIEvent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/title"},{"value":[{"text":"ZDKClassicMessagingUIEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/fragments"},{"value":[{"text":"ZDKClassicMessagingUIEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/navigatorTitle"},{"value":"ZDKClassicMessagingUIEventViewDidLoad","op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewDidLoad\/title"},{"value":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewDidLoad"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewDidLoad\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}