{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"messaging"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","preciseIdentifier":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessaging","text":"Messaging"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didPerformEvent"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent","preciseIdentifier":"c:@M@MessagingSDK@E@ZDKClassicMessagingUIEvent","text":"MessagingUIEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"messaging","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" instance"}]}]},{"name":"event","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"event of type "},{"type":"codeVoice","code":"MessagingUIEvent"}]}]},{"name":"context","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"optional additional context that comes along with the "},{"type":"codeVoice","code":"event"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/messagingsdk\/messagingdelegate\/messaging(_:didperformevent:context:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/messagingsdk\/messagingdelegate\/messaging(_:didperformevent:context:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate\/messaging(_:didPerformEvent:context:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Allows you to observe UI events that occured in "},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":"’s UI."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"messaging:didPerformEvent:context:"}],"role":"symbol","title":"messaging(_:didPerformEvent:context:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Messaging","preciseIdentifier":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessaging"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didPerformEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagingUIEvent","preciseIdentifier":"c:@M@MessagingSDK@E@ZDKClassicMessagingUIEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@M@MessagingSDK@objc(pl)ZDKClassicMessagingDelegate(im)messaging:didPerformEvent:context:","required":true,"modules":[{"name":"MessagingSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate"]]},"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"role":"collection","title":"MessagingSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","kind":"symbol","type":"topic","url":"\/documentation\/messagingsdk"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingDelegate":{"role":"symbol","title":"MessagingDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingDelegate"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagingDelegate"}],"url":"\/documentation\/messagingsdk\/messagingdelegate"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent":{"role":"symbol","title":"MessagingUIEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingUIEvent"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagingUIEvent"}],"url":"\/documentation\/messagingsdk\/messaginguievent"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging":{"role":"symbol","title":"Messaging","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Messaging"}],"abstract":[{"type":"text","text":"The Messaging class coordinates Zendesk’s product UI engines,"},{"type":"text","text":" "},{"type":"text","text":"to allow them to work seamlessly in a single unified messaging interface."}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Messaging"}],"url":"\/documentation\/messagingsdk\/messaging"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingDelegate/messaging(_:didPerformEvent:context:)":{"navigatorTitle":[{"kind":"identifier","text":"messaging:didPerformEvent:context:"}],"role":"symbol","title":"messaging(_:didPerformEvent:context:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Messaging","preciseIdentifier":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessaging"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didPerformEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagingUIEvent","preciseIdentifier":"c:@M@MessagingSDK@E@ZDKClassicMessagingUIEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Allows you to observe UI events that occured in "},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":"’s UI."}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate\/messaging(_:didPerformEvent:context:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/messagingsdk\/messagingdelegate\/messaging(_:didperformevent:context:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"messaging:didPerformEvent:context:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messaging:didPerformEvent:context:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"messaging:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","preciseIdentifier":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessaging","text":"ZDKClassicMessaging"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"messaging"},{"kind":"text","text":" "},{"kind":"identifier","text":"didPerformEvent:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent","preciseIdentifier":"c:@M@MessagingSDK@E@ZDKClassicMessagingUIEvent","text":"ZDKClassicMessagingUIEvent"},{"kind":"text","text":")"},{"kind":"internalParam","text":"event"},{"kind":"text","text":" "},{"kind":"identifier","text":"context:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":")"},{"kind":"internalParam","text":"context"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate\/title","value":"ZDKClassicMessagingDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate\/fragments","value":[{"kind":"identifier","text":"ZDKClassicMessagingDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/title","value":"ZDKClassicMessagingUIEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/fragments","value":[{"kind":"identifier","text":"ZDKClassicMessagingUIEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/title","value":"ZDKClassicMessaging"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/fragments","value":[{"kind":"identifier","text":"ZDKClassicMessaging"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate~1messaging(_:didPerformEvent:context:)\/title","value":"messaging:didPerformEvent:context:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate~1messaging(_:didPerformEvent:context:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messaging:didPerformEvent:context:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}