{"abstract":[{"type":"text","text":"The avatar image for the bot. Default is the Answer Bot avatar."}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration\/botAvatar","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"botAvatar"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/messagingsdk\/messagingconfiguration\/botavatar"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/messagingsdk\/messagingconfiguration\/botavatar"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"botAvatar"}],"externalID":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessagingConfiguration(py)botAvatar","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"botAvatar"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"}],"role":"symbol","title":"botAvatar","modules":[{"name":"MessagingSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration"]]},"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingConfiguration":{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration","role":"symbol","url":"\/documentation\/messagingsdk\/messagingconfiguration","type":"topic","abstract":[{"text":"Class used to configure the Messaging screen.","type":"text"}],"title":"MessagingConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MessagingConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessagingConfiguration"}]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","role":"collection","url":"\/documentation\/messagingsdk","type":"topic","abstract":[],"title":"MessagingSDK","kind":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingConfiguration/botAvatar":{"type":"topic","title":"botAvatar","url":"\/documentation\/messagingsdk\/messagingconfiguration\/botavatar","kind":"symbol","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration\/botAvatar","abstract":[{"type":"text","text":"The avatar image for the bot. Default is the Answer Bot avatar."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"botAvatar","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}],"navigatorTitle":[{"text":"botAvatar","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"botAvatar","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"botAvatar","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" * ","kind":"text"},{"text":"botAvatar","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration\/title","op":"replace","value":"ZDKClassicMessagingConfiguration"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKClassicMessagingConfiguration"}]},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration~1botAvatar\/title","value":"botAvatar","op":"replace"},{"value":[{"text":"botAvatar","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration~1botAvatar\/fragments","op":"replace"}]}]}