{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/messagingsdk\/messaging\/instance"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/messagingsdk\/messaging\/instance"]}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"Messaging"},{"text":" singleton instance","type":"text"}],"sections":[],"metadata":{"roleHeading":"Type Property","symbolKind":"property","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"instance","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessaging","text":"Messaging","kind":"typeIdentifier"}],"title":"instance","navigatorTitle":[{"kind":"identifier","text":"instance"}],"modules":[{"name":"MessagingSDK"}],"externalID":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessaging(cpy)instance"},"identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/instance","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instance","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","preciseIdentifier":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessaging","kind":"typeIdentifier","text":"Messaging"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging/instance":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"instance"}],"abstract":[{"type":"text","text":"The "},{"code":"Messaging","type":"codeVoice"},{"type":"text","text":" singleton instance"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"instance","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessaging","text":"Messaging"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/instance","type":"topic","title":"instance","url":"\/documentation\/messagingsdk\/messaging\/instance"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Messaging"}],"url":"\/documentation\/messagingsdk\/messaging","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","navigatorTitle":[{"kind":"identifier","text":"Messaging"}],"title":"Messaging","kind":"symbol","abstract":[{"type":"text","text":"The Messaging class coordinates Zendesk’s product UI engines,"},{"type":"text","text":" "},{"text":"to allow them to work seamlessly in a single unified messaging interface.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"abstract":[],"title":"MessagingSDK","type":"topic","url":"\/documentation\/messagingsdk","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"instance"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"instance"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","text":"ZDKClassicMessaging","preciseIdentifier":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessaging","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"instance","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging~1instance\/title","op":"replace","value":"instance"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging~1instance\/fragments","value":[{"text":"instance","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/title","value":"ZDKClassicMessaging","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/fragments","value":[{"text":"ZDKClassicMessaging","kind":"identifier"}]}]}]}