{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildUI"},{"kind":"text","text":"("},{"kind":"externalParam","text":"engines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ZDKEngine","preciseIdentifier":"c:@M@MessagingAPI@objc(pl)ZDKEngine"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"configs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An instance of "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" which starts with the first engine in "},{"type":"codeVoice","code":"engines"}]}]},{"kind":"parameters","parameters":[{"name":"engines","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ordered list of engines that will be part of the conversation"}]}]},{"name":"configs","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Configurations for each of your engines"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If no engines were passed"}]}],"type":"aside","name":"Throws"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/messagingsdk\/messaging\/buildui(engines:configs:)-2k264"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/messagingsdk\/messaging\/buildui(engines:configs:)-2k264"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/buildUI(engines:configs:)-2k264","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Objective-C method for building the Messaging “ViewController”"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"buildUIWithEngines:configs:error:"}],"role":"symbol","title":"buildUI(engines:configs:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildUI"},{"kind":"text","text":"("},{"kind":"externalParam","text":"engines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ZDKEngine","preciseIdentifier":"c:@M@MessagingAPI@objc(pl)ZDKEngine"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"configs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"symbolKind":"method","externalID":"c:@CM@MessagingSDK@objc(cs)ZDKClassicMessaging(im)buildUIWithEngines:configs:error:","modules":[{"name":"MessagingSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging"]]},"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging/buildUI(engines:configs:)-2k264":{"role":"symbol","title":"buildUI(engines:configs:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildUI"},{"kind":"text","text":"("},{"kind":"externalParam","text":"engines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ZDKEngine","preciseIdentifier":"c:@M@MessagingAPI@objc(pl)ZDKEngine"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"configs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"Objective-C method for building the Messaging “ViewController”"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/buildUI(engines:configs:)-2k264","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildUIWithEngines:configs:error:"}],"url":"\/documentation\/messagingsdk\/messaging\/buildui(engines:configs:)-2k264"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging":{"role":"symbol","title":"Messaging","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Messaging"}],"abstract":[{"type":"text","text":"The Messaging class coordinates Zendesk’s product UI engines,"},{"type":"text","text":" "},{"type":"text","text":"to allow them to work seamlessly in a single unified messaging interface."}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Messaging"}],"url":"\/documentation\/messagingsdk\/messaging"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"role":"collection","title":"MessagingSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","kind":"symbol","type":"topic","url":"\/documentation\/messagingsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"buildUIWithEngines:configs:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"buildUIWithEngines:configs:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"buildUIWithEngines:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<id<ZDKEngine>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"engines"},{"kind":"text","text":" "},{"kind":"identifier","text":"configs:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<id<ZDKConfiguration>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"configs"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging~1buildUI(engines:configs:)-2k264\/title","value":"buildUIWithEngines:configs:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging~1buildUI(engines:configs:)-2k264\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"buildUIWithEngines:configs:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/title","value":"ZDKClassicMessaging"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/fragments","value":[{"kind":"identifier","text":"ZDKClassicMessaging"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}