{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isMessagingPresented"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/messagingsdk\/messaging\/ismessagingpresented"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/messagingsdk\/messaging\/ismessagingpresented"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/isMessagingPresented","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if Messaging UI is presented"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isMessagingPresented"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isMessagingPresented","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessaging(py)isMessagingPresented","modules":[{"name":"MessagingSDK"}],"navigatorTitle":[{"kind":"identifier","text":"isMessagingPresented"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging"]]},"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging":{"role":"symbol","title":"Messaging","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Messaging"}],"abstract":[{"type":"text","text":"The Messaging class coordinates Zendesk’s product UI engines,"},{"type":"text","text":" "},{"type":"text","text":"to allow them to work seamlessly in a single unified messaging interface."}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Messaging"}],"url":"\/documentation\/messagingsdk\/messaging"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging/isMessagingPresented":{"role":"symbol","title":"isMessagingPresented","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isMessagingPresented"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if Messaging UI is presented"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/isMessagingPresented","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isMessagingPresented"}],"url":"\/documentation\/messagingsdk\/messaging\/ismessagingpresented"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"role":"collection","title":"MessagingSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","kind":"symbol","type":"topic","url":"\/documentation\/messagingsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isMessagingPresented"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isMessagingPresented"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isMessagingPresented"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/title","value":"ZDKClassicMessaging"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/fragments","value":[{"kind":"identifier","text":"ZDKClassicMessaging"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging~1isMessagingPresented\/title","value":"isMessagingPresented"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging~1isMessagingPresented\/fragments","value":[{"kind":"identifier","text":"isMessagingPresented"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}