{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent"},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.zendesk.MessagingSDK\/SQ","doc:\/\/com.zendesk.MessagingSDK\/SH","doc:\/\/com.zendesk.MessagingSDK\/SY"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/messagingsdk\/messaginguievent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/messagingsdk\/messaginguievent"]}],"sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewControllerDidClose","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidAppear","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidDisappear","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidLayoutSubviews","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidLoad","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewWillAppear","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewWillDisappear"]},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/init(rawValue:)"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/Equatable-Implementations","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/RawRepresentable-Implementations"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKClassicMessagingUIEvent) "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessagingUIEvent","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK"]]},"metadata":{"role":"symbol","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MessagingUIEvent","kind":"identifier"}],"roleHeading":"Enumeration","modules":[{"name":"MessagingSDK"}],"navigatorTitle":[{"text":"MessagingUIEvent","kind":"identifier"}],"externalID":"c:@M@MessagingSDK@E@ZDKClassicMessagingUIEvent","title":"MessagingUIEvent"},"kind":"symbol","references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent/viewDidLayoutSubviews":{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidLayoutSubviews","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"}],"url":"\/documentation\/messagingsdk\/messaginguievent\/viewdidlayoutsubviews","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewDidLayoutSubviews"}],"title":"MessagingUIEvent.viewDidLayoutSubviews"},"doc://com.zendesk.MessagingSDK/SQ":{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent/init(rawValue:)":{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/init(rawValue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/messagingsdk\/messaginguievent\/init(rawvalue:)","role":"symbol","type":"topic","abstract":[],"title":"init(rawValue:)"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","role":"collection","url":"\/documentation\/messagingsdk","type":"topic","abstract":[],"title":"MessagingSDK","kind":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent/viewControllerDidClose":{"type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewControllerDidClose","url":"\/documentation\/messagingsdk\/messaginguievent\/viewcontrollerdidclose","abstract":[{"type":"text","text":"Fired once the Messaging UI is closed and no longer visible to the user"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"viewControllerDidClose","kind":"identifier"}],"kind":"symbol","title":"MessagingUIEvent.viewControllerDidClose","navigatorTitle":[{"text":"ZDKClassicMessagingUIEventViewControllerDidClose","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent":{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent","role":"symbol","url":"\/documentation\/messagingsdk\/messaginguievent","type":"topic","abstract":[],"title":"MessagingUIEvent","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingUIEvent"}],"navigatorTitle":[{"text":"MessagingUIEvent","kind":"identifier"}]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent/viewWillDisappear":{"abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewWillDisappear","navigatorTitle":[{"text":"ZDKClassicMessagingUIEventViewWillDisappear","kind":"identifier"}],"title":"MessagingUIEvent.viewWillDisappear","kind":"symbol","url":"\/documentation\/messagingsdk\/messaginguievent\/viewwilldisappear","role":"symbol","type":"topic"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent/viewDidAppear":{"role":"symbol","url":"\/documentation\/messagingsdk\/messaginguievent\/viewdidappear","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidAppear","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"viewDidAppear","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKClassicMessagingUIEventViewDidAppear","kind":"identifier"}],"title":"MessagingUIEvent.viewDidAppear"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent/viewDidDisappear":{"title":"MessagingUIEvent.viewDidDisappear","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidDisappear","role":"symbol","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"ZDKClassicMessagingUIEventViewDidDisappear","kind":"identifier"}],"url":"\/documentation\/messagingsdk\/messaginguievent\/viewdiddisappear","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidDisappear","kind":"identifier"}]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent/Equatable-Implementations":{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","abstract":[],"type":"topic","url":"\/documentation\/messagingsdk\/messaginguievent\/equatable-implementations","kind":"article"},"doc://com.zendesk.MessagingSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.MessagingSDK\/SY","title":"Swift.RawRepresentable"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent/viewDidLoad":{"navigatorTitle":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewDidLoad"}],"title":"MessagingUIEvent.viewDidLoad","type":"topic","url":"\/documentation\/messagingsdk\/messaginguievent\/viewdidload","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidLoad","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","kind":"article","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/RawRepresentable-Implementations","url":"\/documentation\/messagingsdk\/messaginguievent\/rawrepresentable-implementations","role":"collectionGroup","type":"topic","abstract":[]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent/viewWillAppear":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewWillAppear","kind":"identifier"}],"url":"\/documentation\/messagingsdk\/messaginguievent\/viewwillappear","kind":"symbol","title":"MessagingUIEvent.viewWillAppear","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewWillAppear","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"ZDKClassicMessagingUIEventViewWillAppear","kind":"identifier"}]},"doc://com.zendesk.MessagingSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.MessagingSDK\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKClassicMessagingUIEvent"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKClassicMessagingUIEvent"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"ZDKClassicMessagingUIEvent","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewControllerDidClose","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidAppear","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidDisappear","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidLayoutSubviews","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidLoad","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewWillAppear","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewWillDisappear"],"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKClassicMessagingUIEvent","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewDidLayoutSubviews\/title","value":"ZDKClassicMessagingUIEventViewDidLayoutSubviews","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewDidLayoutSubviews\/fragments","value":[{"text":"ZDKClassicMessagingUIEventViewDidLayoutSubviews","kind":"identifier"}],"op":"replace"},{"value":"ZDKClassicMessagingUIEventViewControllerDidClose","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewControllerDidClose\/title","op":"replace"},{"value":[{"text":"ZDKClassicMessagingUIEventViewControllerDidClose","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewControllerDidClose\/fragments"},{"value":"ZDKClassicMessagingUIEvent","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/fragments","value":[{"text":"ZDKClassicMessagingUIEvent","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewWillDisappear\/title","value":"ZDKClassicMessagingUIEventViewWillDisappear"},{"value":[{"text":"ZDKClassicMessagingUIEventViewWillDisappear","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewWillDisappear\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewDidAppear\/title","value":"ZDKClassicMessagingUIEventViewDidAppear"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewDidAppear\/fragments","value":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewDidAppear"}]},{"value":"ZDKClassicMessagingUIEventViewDidDisappear","op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewDidDisappear\/title"},{"value":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewDidDisappear"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewDidDisappear\/fragments"},{"value":"ZDKClassicMessagingUIEventViewDidLoad","op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewDidLoad\/title"},{"value":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewDidLoad"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewDidLoad\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewWillAppear\/title","value":"ZDKClassicMessagingUIEventViewWillAppear"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewWillAppear\/fragments","value":[{"text":"ZDKClassicMessagingUIEventViewWillAppear","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}