{"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/delegate","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MessagingDelegate","preciseIdentifier":"c:@M@MessagingSDK@objc(pl)ZDKClassicMessagingDelegate","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/messagingsdk\/messaging\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/messagingsdk\/messaging\/delegate"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging"]]},"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MessagingSDK@objc(pl)ZDKClassicMessagingDelegate","text":"MessagingDelegate"},{"kind":"text","text":"?"}],"externalID":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessaging(py)delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"modules":[{"name":"MessagingSDK"}],"role":"symbol","title":"delegate","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Messaging delegate allows you to observe user events that happen in the "},{"type":"codeVoice","code":"MessagingSDK"},{"type":"text","text":"."}],"sections":[],"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging/delegate":{"type":"topic","kind":"symbol","role":"symbol","title":"delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MessagingSDK@objc(pl)ZDKClassicMessagingDelegate","text":"MessagingDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/messagingsdk\/messaging\/delegate","abstract":[{"type":"text","text":"Messaging delegate allows you to observe user events that happen in the "},{"type":"codeVoice","code":"MessagingSDK"},{"type":"text","text":"."}]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","role":"collection","title":"MessagingSDK","abstract":[],"kind":"symbol","url":"\/documentation\/messagingsdk"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging":{"role":"symbol","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Messaging","kind":"identifier"}],"url":"\/documentation\/messagingsdk\/messaging","title":"Messaging","abstract":[{"type":"text","text":"The Messaging class coordinates Zendesk’s product UI engines,"},{"type":"text","text":" "},{"type":"text","text":"to allow them to work seamlessly in a single unified messaging interface."}],"kind":"symbol","navigatorTitle":[{"text":"Messaging","kind":"identifier"}]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingDelegate","kind":"identifier"}],"url":"\/documentation\/messagingsdk\/messagingdelegate","role":"symbol","navigatorTitle":[{"text":"MessagingDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate","kind":"symbol","title":"MessagingDelegate","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"delegate","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<ZDKClassicMessagingDelegate>","preciseIdentifier":"c:Qo@M@MessagingSDK@objc(pl)ZDKClassicMessagingDelegate","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"delegate","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging~1delegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging~1delegate\/fragments","op":"replace"},{"value":"ZDKClassicMessaging","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKClassicMessaging"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKClassicMessaging"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/navigatorTitle","op":"replace"},{"value":"ZDKClassicMessagingDelegate","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKClassicMessagingDelegate"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKClassicMessagingDelegate"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}