{"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"text":"Class used to configure the Messaging screen.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKClassicMessagingConfiguration) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingConfiguration","kind":"identifier"}]}],"kind":"declarations"},{"content":[{"text":"Overview","level":2,"anchor":"overview","type":"heading"},{"name":"Version","style":"note","content":[{"inlineContent":[{"type":"text","text":"1.0.0"}],"type":"paragraph"}],"type":"aside"}],"kind":"content"}],"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration\/botAvatar","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration\/isMultilineResponseOptionsEnabled","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration\/name"],"generated":true,"title":"Instance Properties"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.MessagingSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/com.zendesk.MessagingSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.MessagingSDK\/@M@SDKConfigurations@objc(pl)ZDKConfiguration","doc:\/\/com.zendesk.MessagingSDK\/s7CVarArgP","doc:\/\/com.zendesk.MessagingSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.MessagingSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.MessagingSDK\/SQ","doc:\/\/com.zendesk.MessagingSDK\/SH"],"title":"Conforms To","kind":"relationships"}],"metadata":{"roleHeading":"Class","externalID":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessagingConfiguration","title":"MessagingConfiguration","modules":[{"name":"MessagingSDK"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MessagingConfiguration","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/messagingsdk\/messagingconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/messagingsdk\/messagingconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.MessagingSDK/@M@SDKConfigurations@objc(pl)ZDKConfiguration":{"title":"ZDKConfiguration","type":"unresolvable","identifier":"doc:\/\/com.zendesk.MessagingSDK\/@M@SDKConfigurations@objc(pl)ZDKConfiguration"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingConfiguration/botAvatar":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"botAvatar"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration\/botAvatar","navigatorTitle":[{"kind":"identifier","text":"botAvatar"}],"abstract":[{"type":"text","text":"The avatar image for the bot. Default is the Answer Bot avatar."}],"title":"botAvatar","role":"symbol","url":"\/documentation\/messagingsdk\/messagingconfiguration\/botavatar","type":"topic","kind":"symbol"},"doc://com.zendesk.MessagingSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.zendesk.MessagingSDK\/objc(cs)NSObject"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"title":"MessagingSDK","type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","role":"collection","url":"\/documentation\/messagingsdk","kind":"symbol","abstract":[]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingConfiguration/isMultilineResponseOptionsEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isMultilineResponseOptionsEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"isMultilineResponseOptionsEnabled","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration\/isMultilineResponseOptionsEnabled","title":"isMultilineResponseOptionsEnabled","abstract":[{"text":"Flag to enable whether the user response options will span across multiple lines, or just have one line.","type":"text"}],"url":"\/documentation\/messagingsdk\/messagingconfiguration\/ismultilineresponseoptionsenabled","kind":"symbol"},"doc://com.zendesk.MessagingSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.MessagingSDK\/SH"},"doc://com.zendesk.MessagingSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.MessagingSDK\/s7CVarArgP"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingConfiguration":{"abstract":[{"text":"Class used to configure the Messaging screen.","type":"text"}],"type":"topic","title":"MessagingConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingConfiguration"}],"kind":"symbol","url":"\/documentation\/messagingsdk\/messagingconfiguration","navigatorTitle":[{"text":"MessagingConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration"},"doc://com.zendesk.MessagingSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.MessagingSDK\/SQ"},"doc://com.zendesk.MessagingSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.zendesk.MessagingSDK\/objc(pl)NSObject"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingConfiguration/name":{"abstract":[{"type":"text","text":"The name of bot shown in the UI. Default is “Answer Bot”."}],"navigatorTitle":[{"kind":"identifier","text":"name"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration\/name","title":"name","url":"\/documentation\/messagingsdk\/messagingconfiguration\/name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","role":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/ZDKClassicMessagingConfiguration/init":{"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/messagingsdk\/zdkclassicmessagingconfiguration\/init","title":"init","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/ZDKClassicMessagingConfiguration\/init"},"doc://com.zendesk.MessagingSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.MessagingSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.MessagingSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.MessagingSDK\/s23CustomStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"ZDKClassicMessagingConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKClassicMessagingConfiguration"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKClassicMessagingConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration\/botAvatar","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration\/isMultilineResponseOptionsEnabled","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration\/name"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/ZDKClassicMessagingConfiguration\/init"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.MessagingSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.zendesk.MessagingSDK\/@M@SDKConfigurations@objc(pl)ZDKConfiguration"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKClassicMessagingConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration~1botAvatar\/title","value":"botAvatar","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration~1botAvatar\/fragments","value":[{"text":"botAvatar","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration~1isMultilineResponseOptionsEnabled\/title","value":"isMultilineResponseOptionsEnabled","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration~1isMultilineResponseOptionsEnabled\/fragments","value":[{"text":"isMultilineResponseOptionsEnabled","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration\/title","value":"ZDKClassicMessagingConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration\/fragments","value":[{"kind":"identifier","text":"ZDKClassicMessagingConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKClassicMessagingConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration~1name\/title","value":"name","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration~1name\/fragments","value":[{"text":"name","kind":"identifier"}],"op":"replace"}]}]}