{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/messagingsdk\/messaginguievent\/viewwilldisappear"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/messagingsdk\/messaginguievent\/viewwilldisappear"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewWillDisappear","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent"]]},"metadata":{"externalID":"c:@M@MessagingSDK@E@ZDKClassicMessagingUIEvent@ZDKClassicMessagingUIEventViewWillDisappear","navigatorTitle":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewWillDisappear"}],"title":"MessagingUIEvent.viewWillDisappear","roleHeading":"Case","modules":[{"name":"MessagingSDK"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"}],"role":"symbol"},"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"title":"MessagingSDK","type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","role":"collection","url":"\/documentation\/messagingsdk","kind":"symbol","abstract":[]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent/viewWillDisappear":{"role":"symbol","kind":"symbol","title":"MessagingUIEvent.viewWillDisappear","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"}],"url":"\/documentation\/messagingsdk\/messaginguievent\/viewwilldisappear","abstract":[],"navigatorTitle":[{"text":"ZDKClassicMessagingUIEventViewWillDisappear","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewWillDisappear"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent":{"type":"topic","kind":"symbol","url":"\/documentation\/messagingsdk\/messaginguievent","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessagingUIEvent"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent","abstract":[],"title":"MessagingUIEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingUIEvent"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKClassicMessagingUIEventViewWillDisappear","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKClassicMessagingUIEventViewWillDisappear","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewWillDisappear"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewWillDisappear\/title","value":"ZDKClassicMessagingUIEventViewWillDisappear"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewWillDisappear\/fragments","value":[{"text":"ZDKClassicMessagingUIEventViewWillDisappear","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/title","value":"ZDKClassicMessagingUIEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/fragments","value":[{"text":"ZDKClassicMessagingUIEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/navigatorTitle","value":[{"text":"ZDKClassicMessagingUIEvent","kind":"identifier"}]}]}]}