{"topicSections":[{"identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/DispatchTimer","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration"],"title":"Classes"},{"title":"Protocols","identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate"]},{"title":"Enumerations","identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent"]},{"identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingAPI"],"title":"Extended Modules"}],"hierarchy":{"paths":[[]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/messagingsdk"]},{"paths":["\/documentation\/messagingsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","interfaceLanguage":"swift"},"metadata":{"externalID":"MessagingSDK","role":"collection","title":"MessagingSDK","symbolKind":"module","roleHeading":"Framework","modules":[{"name":"MessagingSDK"}]},"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingAPI":{"role":"collection","type":"topic","abstract":[],"title":"MessagingAPI","kind":"symbol","url":"\/documentation\/messagingsdk\/messagingapi","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingAPI"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Messaging"}],"url":"\/documentation\/messagingsdk\/messaging","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","navigatorTitle":[{"kind":"identifier","text":"Messaging"}],"title":"Messaging","kind":"symbol","abstract":[{"type":"text","text":"The Messaging class coordinates Zendesk’s product UI engines,"},{"type":"text","text":" "},{"text":"to allow them to work seamlessly in a single unified messaging interface.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingSDKVersionNumber":{"role":"symbol","url":"\/documentation\/messagingsdk\/messagingsdkversionnumber","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingSDKVersionNumber","type":"topic","title":"MessagingSDKVersionNumber","abstract":[{"type":"text","text":"Project version number for MessagingSDK."}],"fragments":[{"kind":"identifier","text":"MessagingSDKVersionNumber"}],"kind":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/DispatchTimer":{"role":"symbol","url":"\/documentation\/messagingsdk\/dispatchtimer","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/DispatchTimer","type":"topic","title":"DispatchTimer","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DispatchTimer"}],"navigatorTitle":[{"kind":"identifier","text":"DispatchTimer"}],"kind":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingConfiguration":{"abstract":[{"text":"Class used to configure the Messaging screen.","type":"text"}],"navigatorTitle":[{"text":"MessagingConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration","title":"MessagingConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MessagingConfiguration","kind":"identifier"}],"url":"\/documentation\/messagingsdk\/messagingconfiguration","kind":"symbol","type":"topic","role":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingDelegate":{"role":"symbol","url":"\/documentation\/messagingsdk\/messagingdelegate","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate","type":"topic","title":"MessagingDelegate","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingDelegate"}],"navigatorTitle":[{"text":"MessagingDelegate","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingUIEvent"}],"type":"topic","url":"\/documentation\/messagingsdk\/messaginguievent","navigatorTitle":[{"text":"MessagingUIEvent","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent","title":"MessagingUIEvent","kind":"symbol","role":"symbol","abstract":[]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingSDKVersionString":{"role":"symbol","url":"\/documentation\/messagingsdk\/messagingsdkversionstring","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingSDKVersionString","type":"topic","title":"MessagingSDKVersionString","abstract":[{"text":"Project version string for MessagingSDK.","type":"text"}],"fragments":[{"kind":"identifier","text":"MessagingSDKVersionString"}],"kind":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"abstract":[],"title":"MessagingSDK","type":"topic","url":"\/documentation\/messagingsdk","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"title":"Classes","identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration"]},{"identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate"],"title":"Protocols"},{"title":"Variables","identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingSDKVersionNumber","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingSDKVersionString"]},{"identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent"],"title":"Enumerations"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/title","value":"ZDKClassicMessaging","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/fragments","value":[{"kind":"identifier","text":"ZDKClassicMessaging"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration\/title","value":"ZDKClassicMessagingConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKClassicMessagingConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate\/title","value":"ZDKClassicMessagingDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate\/fragments","value":[{"kind":"identifier","text":"ZDKClassicMessagingDelegate"}],"op":"replace"},{"op":"replace","value":"ZDKClassicMessagingUIEvent","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/title"},{"value":[{"kind":"identifier","text":"ZDKClassicMessagingUIEvent"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}