{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"getBotAgentDetails()","roleHeading":"Instance Method","extendedModule":"MessagingSDK","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBotAgentDetails"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI12AgentDetailsV","text":"AgentDetails"}],"externalID":"s:12MessagingSDK0A0C18getBotAgentDetails0A3API0eF0VyF","modules":[{"name":"MessagingSDK"}],"symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/messagingsdk\/messaging\/getbotagentdetails()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/getBotAgentDetails()"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBotAgentDetails"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:12MessagingAPI12AgentDetailsV","kind":"typeIdentifier","text":"AgentDetails"}]}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"MessagingAPIProtocol.getBotAgentDetails()"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging"]]},"kind":"symbol","references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging/getBotAgentDetails()":{"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBotAgentDetails"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:12MessagingAPI12AgentDetailsV","kind":"typeIdentifier","text":"AgentDetails"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/getBotAgentDetails()","type":"topic","role":"symbol","url":"\/documentation\/messagingsdk\/messaging\/getbotagentdetails()","kind":"symbol","title":"getBotAgentDetails()"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"title":"MessagingSDK","type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","role":"collection","url":"\/documentation\/messagingsdk","kind":"symbol","abstract":[]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging":{"navigatorTitle":[{"text":"Messaging","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","title":"Messaging","role":"symbol","url":"\/documentation\/messagingsdk\/messaging","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Messaging","kind":"identifier"}],"abstract":[{"text":"The Messaging class coordinates Zendesk’s product UI engines,","type":"text"},{"text":" ","type":"text"},{"text":"to allow them to work seamlessly in a single unified messaging interface.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/title","op":"replace","value":"ZDKClassicMessaging"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/fragments","op":"replace","value":[{"text":"ZDKClassicMessaging","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/navigatorTitle","op":"replace","value":[{"text":"ZDKClassicMessaging","kind":"identifier"}]}]}]}