{"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"MessagingAPIProtocol.getConversationLog()"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/getConversationLog()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"role":"symbol","externalID":"s:12MessagingSDK0A0C18getConversationLog0A3API0dE8Protocol_pyF","title":"getConversationLog()","extendedModule":"MessagingSDK","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getConversationLog","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:12MessagingAPI23ConversationLogProtocolP","text":"ConversationLogProtocol","kind":"typeIdentifier"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"MessagingSDK"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/messagingsdk\/messaging\/getconversationlog()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getConversationLog"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:12MessagingAPI23ConversationLogProtocolP","kind":"typeIdentifier","text":"ConversationLogProtocol"}]}]}],"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging/getConversationLog()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getConversationLog","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:12MessagingAPI23ConversationLogProtocolP","text":"ConversationLogProtocol","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/getConversationLog()","role":"symbol","abstract":[],"title":"getConversationLog()","kind":"symbol","url":"\/documentation\/messagingsdk\/messaging\/getconversationlog()"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"title":"MessagingSDK","type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","role":"collection","url":"\/documentation\/messagingsdk","kind":"symbol","abstract":[]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging":{"navigatorTitle":[{"text":"Messaging","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","title":"Messaging","role":"symbol","url":"\/documentation\/messagingsdk\/messaging","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Messaging","kind":"identifier"}],"abstract":[{"text":"The Messaging class coordinates Zendesk’s product UI engines,","type":"text"},{"text":" ","type":"text"},{"text":"to allow them to work seamlessly in a single unified messaging interface.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"ZDKClassicMessaging","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKClassicMessaging"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKClassicMessaging"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}