{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/messagingsdk\/messagingconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration\/init","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessagingConfiguration(im)init","modules":[{"name":"MessagingSDK"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration"]]},"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"role":"collection","title":"MessagingSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","kind":"symbol","type":"topic","url":"\/documentation\/messagingsdk"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingConfiguration/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/messagingsdk\/messagingconfiguration\/init"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingConfiguration":{"role":"symbol","title":"MessagingConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingConfiguration"}],"abstract":[{"type":"text","text":"Class used to configure the Messaging screen."}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagingConfiguration"}],"url":"\/documentation\/messagingsdk\/messagingconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration\/title","value":"ZDKClassicMessagingConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration\/fragments","value":[{"kind":"identifier","text":"ZDKClassicMessagingConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}