{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/messagingsdk\/messagingconfiguration\/ismultilineresponseoptionsenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/messagingsdk\/messagingconfiguration\/ismultilineresponseoptionsenabled"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Flag to enable whether the user response options will span across multiple lines, or just have one line.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isMultilineResponseOptionsEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}]},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"false"},{"text":":  ","type":"text"},{"code":"ResponseOptions","type":"codeVoice"},{"text":" appear in a ","type":"text"},{"code":"UICollectionView","type":"codeVoice"},{"text":" which scrolls horizontally","type":"text"},{"text":" ","type":"text"},{"text":"if the ","type":"text"},{"code":"contentSize.width","type":"codeVoice"},{"text":" is greater than the collectionView’s","type":"text"},{"code":"frame.width","type":"codeVoice"}]}]},{"content":[{"inlineContent":[{"code":"true","type":"codeVoice"},{"text":": ","type":"text"},{"code":"ResponseOptions","type":"codeVoice"},{"text":" appear in a ","type":"text"},{"code":"UICollectionView","type":"codeVoice"},{"text":" which expands vertically to fit all the content on screen","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"eg. AnswerBot response options or Chat’s pre-chat form department selection."}]}],"kind":"content"}],"sections":[],"metadata":{"title":"isMultilineResponseOptionsEnabled","role":"symbol","externalID":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessagingConfiguration(py)isMultilineResponseOptionsEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isMultilineResponseOptionsEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"property","navigatorTitle":[{"text":"isMultilineResponseOptionsEnabled","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"MessagingSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration\/isMultilineResponseOptionsEnabled"},"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingConfiguration":{"abstract":[{"text":"Class used to configure the Messaging screen.","type":"text"}],"type":"topic","title":"MessagingConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingConfiguration"}],"kind":"symbol","url":"\/documentation\/messagingsdk\/messagingconfiguration","navigatorTitle":[{"text":"MessagingConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingConfiguration/isMultilineResponseOptionsEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isMultilineResponseOptionsEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"isMultilineResponseOptionsEnabled","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingConfiguration\/isMultilineResponseOptionsEnabled","title":"isMultilineResponseOptionsEnabled","abstract":[{"text":"Flag to enable whether the user response options will span across multiple lines, or just have one line.","type":"text"}],"url":"\/documentation\/messagingsdk\/messagingconfiguration\/ismultilineresponseoptionsenabled","kind":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"title":"MessagingSDK","type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","role":"collection","url":"\/documentation\/messagingsdk","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"isMultilineResponseOptionsEnabled","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"isMultilineResponseOptionsEnabled"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isMultilineResponseOptionsEnabled","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKClassicMessagingConfiguration","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration\/fragments","value":[{"text":"ZDKClassicMessagingConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKClassicMessagingConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration~1isMultilineResponseOptionsEnabled\/title","value":"isMultilineResponseOptionsEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingConfiguration~1isMultilineResponseOptionsEnabled\/fragments","value":[{"kind":"identifier","text":"isMultilineResponseOptionsEnabled"}]}]}]}