{"abstract":[{"type":"text","text":"The Messaging class coordinates Zendesk’s product UI engines,"},{"text":" ","type":"text"},{"text":"to allow them to work seamlessly in a single unified messaging interface.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/delegate","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/isMessagingPresented"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/buildUI(engines:configs:)-2k264","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/buildUI(engines:configs:)-8o1v"]},{"identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/instance"],"title":"Type Properties"},{"identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/MessagingAPIProtocol-Implementations","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/MessagingCoordinatorDelegate-Implementations"],"generated":true,"title":"Default Implementations"}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.MessagingSDK\/objc(cs)NSObject"],"kind":"relationships"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.MessagingSDK\/11CommonUISDK28MessagingCoordinatorDelegateP","doc:\/\/com.zendesk.MessagingSDK\/12MessagingAPI0A11APIProtocolP","doc:\/\/com.zendesk.MessagingSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.MessagingSDK\/s7CVarArgP","doc:\/\/com.zendesk.MessagingSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.MessagingSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.MessagingSDK\/SQ","doc:\/\/com.zendesk.MessagingSDK\/SH"],"type":"conformsTo"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(ZDKClassicMessaging) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Messaging","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":" can be built, once the Messaging singleton is initialized successfully.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This will allow an end-user to start their customer support experience."},{"type":"text","text":" "},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" contains a list of "},{"type":"codeVoice","code":"Engines"},{"type":"text","text":" which map to different"},{"type":"text","text":" "},{"type":"text","text":"Zendesk SDKs like AnswerBot, Chat, and Support."}]}],"kind":"content"}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Messaging"}],"modules":[{"name":"MessagingSDK"}],"roleHeading":"Class","symbolKind":"class","externalID":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessaging","title":"Messaging","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Messaging","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/messagingsdk\/messaging"]},{"paths":["\/documentation\/messagingsdk\/messaging"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.zendesk.MessagingSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.MessagingSDK\/SQ"},"doc://com.zendesk.MessagingSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.MessagingSDK\/objc(cs)NSObject"},"doc://com.zendesk.MessagingSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.MessagingSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging":{"abstract":[{"text":"The Messaging class coordinates Zendesk’s product UI engines,","type":"text"},{"type":"text","text":" "},{"text":"to allow them to work seamlessly in a single unified messaging interface.","type":"text"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Messaging","kind":"identifier"}],"url":"\/documentation\/messagingsdk\/messaging","kind":"symbol","title":"Messaging","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Messaging"}],"type":"topic"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging/buildUI(engines:configs:)-8o1v":{"abstract":[{"text":"Builds the Messaging UI ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":".","type":"text"}],"title":"buildUI(engines:configs:)","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/buildUI(engines:configs:)-8o1v","kind":"symbol","role":"symbol","url":"\/documentation\/messagingsdk\/messaging\/buildui(engines:configs:)-8o1v","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildUI"},{"kind":"text","text":"("},{"text":"engines","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Engine","preciseIdentifier":"s:12MessagingAPI6EngineP","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"configs"},{"text":": [","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"}]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"url":"\/documentation\/messagingsdk","type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","abstract":[],"title":"MessagingSDK","kind":"symbol","role":"collection"},"doc://com.zendesk.MessagingSDK/12MessagingAPI0A11APIProtocolP":{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/12MessagingAPI0A11APIProtocolP","title":"MessagingAPI.MessagingAPIProtocol","type":"unresolvable"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging/buildUI(engines:configs:)-2k264":{"abstract":[{"type":"text","text":"Objective-C method for building the Messaging “ViewController”"}],"title":"buildUI(engines:configs:)","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/buildUI(engines:configs:)-2k264","kind":"symbol","role":"symbol","url":"\/documentation\/messagingsdk\/messaging\/buildui(engines:configs:)-2k264","navigatorTitle":[{"text":"buildUIWithEngines:configs:error:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buildUI"},{"text":"(","kind":"text"},{"text":"engines","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MessagingAPI@objc(pl)ZDKEngine","text":"ZDKEngine"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"configs"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","kind":"typeIdentifier","text":"Configuration"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging/isMessagingPresented":{"abstract":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":" if Messaging UI is presented"}],"title":"isMessagingPresented","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/isMessagingPresented","kind":"symbol","role":"symbol","url":"\/documentation\/messagingsdk\/messaging\/ismessagingpresented","navigatorTitle":[{"kind":"identifier","text":"isMessagingPresented"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isMessagingPresented","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging/MessagingCoordinatorDelegate-Implementations":{"abstract":[],"title":"MessagingCoordinatorDelegate Implementations","type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/MessagingCoordinatorDelegate-Implementations","kind":"article","url":"\/documentation\/messagingsdk\/messaging\/messagingcoordinatordelegate-implementations","role":"collectionGroup"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging/delegate":{"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/delegate","title":"delegate","url":"\/documentation\/messagingsdk\/messaging\/delegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MessagingSDK@objc(pl)ZDKClassicMessagingDelegate","text":"MessagingDelegate"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"text":"Messaging delegate allows you to observe user events that happen in the ","type":"text"},{"code":"MessagingSDK","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging/MessagingAPIProtocol-Implementations":{"role":"collectionGroup","url":"\/documentation\/messagingsdk\/messaging\/messagingapiprotocol-implementations","type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/MessagingAPIProtocol-Implementations","kind":"article","abstract":[],"title":"MessagingAPIProtocol Implementations"},"doc://com.zendesk.MessagingSDK/11CommonUISDK28MessagingCoordinatorDelegateP":{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/11CommonUISDK28MessagingCoordinatorDelegateP","title":"CommonUISDK.MessagingCoordinatorDelegate","type":"unresolvable"},"doc://com.zendesk.MessagingSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.MessagingSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.zendesk.MessagingSDK/SH":{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/Messaging/instance":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"instance","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Messaging","preciseIdentifier":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessaging"}],"url":"\/documentation\/messagingsdk\/messaging\/instance","title":"instance","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"instance","kind":"identifier"}],"type":"topic","abstract":[{"text":"The ","type":"text"},{"code":"Messaging","type":"codeVoice"},{"type":"text","text":" singleton instance"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/instance"},"doc://com.zendesk.MessagingSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.MessagingSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"ZDKClassicMessaging","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"ZDKClassicMessaging","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKClassicMessaging"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/delegate","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/isMessagingPresented"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/buildUI(engines:configs:)-2k264"]},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/Messaging\/instance"]}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.MessagingSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKClassicMessaging","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/title","op":"replace","value":"ZDKClassicMessaging"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKClassicMessaging"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging~1buildUI(engines:configs:)-2k264\/title","value":"buildUIWithEngines:configs:error:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"buildUIWithEngines:configs:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging~1buildUI(engines:configs:)-2k264\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging~1isMessagingPresented\/title","value":"isMessagingPresented"},{"value":[{"kind":"identifier","text":"isMessagingPresented"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging~1isMessagingPresented\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging~1delegate\/title","value":"delegate"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"value":"instance","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging~1instance\/title","op":"replace"},{"op":"replace","value":[{"text":"instance","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1Messaging~1instance\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}