{"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK"]]},"metadata":{"symbolKind":"protocol","externalID":"c:@M@MessagingSDK@objc(pl)ZDKClassicMessagingDelegate","modules":[{"name":"MessagingSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingDelegate"}],"roleHeading":"Protocol","navigatorTitle":[{"text":"MessagingDelegate","kind":"identifier"}],"title":"MessagingDelegate"},"identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate\/messaging(_:didPerformEvent:context:)","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate\/messaging(_:shouldOpenURL:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKClassicMessagingDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingDelegate"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/messagingsdk\/messagingdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/messagingsdk\/messagingdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","role":"collection","title":"MessagingSDK","abstract":[],"kind":"symbol","url":"\/documentation\/messagingsdk"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingDelegate/messaging(_:shouldOpenURL:)":{"abstract":[{"text":"Optional ","type":"text"},{"code":"MessagingDelegate","type":"codeVoice"},{"text":" method that allows custom URL link handling.","type":"text"}],"url":"\/documentation\/messagingsdk\/messagingdelegate\/messaging(_:shouldopenurl:)","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate\/messaging(_:shouldOpenURL:)","role":"symbol","title":"messaging(_:shouldOpenURL:)","navigatorTitle":[{"kind":"identifier","text":"messaging:shouldOpenURL:"}],"required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Messaging","preciseIdentifier":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessaging","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldOpenURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingDelegate","kind":"identifier"}],"url":"\/documentation\/messagingsdk\/messagingdelegate","role":"symbol","navigatorTitle":[{"text":"MessagingDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate","kind":"symbol","title":"MessagingDelegate","abstract":[]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingDelegate/messaging(_:didPerformEvent:context:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Messaging","kind":"typeIdentifier","preciseIdentifier":"c:@M@MessagingSDK@objc(cs)ZDKClassicMessaging"},{"text":", ","kind":"text"},{"text":"didPerformEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessagingUIEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@MessagingSDK@E@ZDKClassicMessagingUIEvent"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"role":"symbol","kind":"symbol","title":"messaging(_:didPerformEvent:context:)","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate\/messaging(_:didPerformEvent:context:)","abstract":[{"text":"Allows you to observe UI events that occured in ","type":"text"},{"code":"Messaging","type":"codeVoice"},{"text":"’s UI.","type":"text"}],"required":true,"type":"topic","navigatorTitle":[{"text":"messaging:didPerformEvent:context:","kind":"identifier"}],"url":"\/documentation\/messagingsdk\/messagingdelegate\/messaging(_:didperformevent:context:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKClassicMessagingDelegate","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ZDKClassicMessagingDelegate","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"ZDKClassicMessagingDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate\/messaging(_:didPerformEvent:context:)","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingDelegate\/messaging(_:shouldOpenURL:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKClassicMessagingDelegate","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"messaging:shouldOpenURL:","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate~1messaging(_:shouldOpenURL:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messaging:shouldOpenURL:"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate~1messaging(_:shouldOpenURL:)\/fragments"},{"op":"replace","value":"ZDKClassicMessagingDelegate","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate\/title"},{"op":"replace","value":[{"text":"ZDKClassicMessagingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate\/navigatorTitle","value":[{"text":"ZDKClassicMessagingDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate~1messaging(_:didPerformEvent:context:)\/title","value":"messaging:didPerformEvent:context:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingDelegate~1messaging(_:didPerformEvent:context:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messaging:didPerformEvent:context:"}]}]}]}