{"sections":[],"metadata":{"roleHeading":"Case","role":"symbol","modules":[{"name":"MessagingSDK"}],"symbolKind":"case","externalID":"c:@M@MessagingSDK@E@ZDKClassicMessagingUIEvent@ZDKClassicMessagingUIEventViewDidDisappear","navigatorTitle":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewDidDisappear"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidDisappear"}],"title":"MessagingUIEvent.viewDidDisappear"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidDisappear","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidDisappear"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/messagingsdk\/messaginguievent\/viewdiddisappear"]},{"paths":["\/documentation\/messagingsdk\/messaginguievent\/viewdiddisappear"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessagingUIEvent"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent","url":"\/documentation\/messagingsdk\/messaginguievent","title":"MessagingUIEvent","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagingUIEvent"}],"abstract":[]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK/MessagingUIEvent/viewDidDisappear":{"navigatorTitle":[{"kind":"identifier","text":"ZDKClassicMessagingUIEventViewDidDisappear"}],"role":"symbol","kind":"symbol","type":"topic","title":"MessagingUIEvent.viewDidDisappear","url":"\/documentation\/messagingsdk\/messaginguievent\/viewdiddisappear","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidDisappear"}],"identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK\/MessagingUIEvent\/viewDidDisappear","abstract":[]},"doc://com.zendesk.MessagingSDK/documentation/MessagingSDK":{"url":"\/documentation\/messagingsdk","type":"topic","identifier":"doc:\/\/com.zendesk.MessagingSDK\/documentation\/MessagingSDK","abstract":[],"title":"MessagingSDK","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKClassicMessagingUIEventViewDidDisappear"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKClassicMessagingUIEventViewDidDisappear","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ZDKClassicMessagingUIEventViewDidDisappear","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKClassicMessagingUIEvent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/title"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent\/fragments","value":[{"text":"ZDKClassicMessagingUIEvent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewDidDisappear\/title","value":"ZDKClassicMessagingUIEventViewDidDisappear","op":"replace"},{"op":"replace","value":[{"text":"ZDKClassicMessagingUIEventViewDidDisappear","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.MessagingSDK~1documentation~1MessagingSDK~1MessagingUIEvent~1viewDidDisappear\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}